### ISSUE TITLE
Log4j - Vulnerability Fix

### ISSUE THREAD

**Issue by mba484** [thoughtworks/metrik#102]
Hello Team,

With the recent Log4j vulnerability, we have found that the current release of the docker image for Dora Metrics has issues.

Are we planning to update the docker images with the latest upgrade(log4j)/ fix for the issue.

Many thanks,
Mohammed

**Comment by hyrepo** [comment]
Fixed by #103

**Comment by ashish-kumar-soni** [comment]
@hyrepo Can you please plan a release for this fix? Thanks in advance.

**Comment by hyrepo** [comment]
@ashish-kumar-soni Just released it in [1.4.0](https://github.com/thoughtworks/metrik/releases/tag/1.4.0).
