### ISSUE TITLE
Out of range of int when parsing github actions run id

### ISSUE THREAD

**Issue by paumanrique5699** [thoughtworks/metrik#111]
**Describe the bug**
Hello! I've been trying to use metrik with github actions, but I am having an issue when configuring a pipeline. After adding the Repository Name, URL and Personal Access Token, when verifying I get the following error:

`{"status":500,"message":"Error while extracting response for type [class metrik.project.infrastructure.github.feign.response.MultipleRunResponse] and content type [application/json;charset=utf-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Numeric value (2167882875) out of range of int (-2147483648 - 2147483647); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2167882875) out of range of int (-2147483648 - 2147483647)\n at [Source: (PushbackInputStream); line: 1, column: 53] (through reference chain: metrik.project.infrastructure.github.feign.response.MultipleRunResponse[\"workflow_runs\"]->java.util.ArrayList[0]->metrik.project.infrastructure.github.feign.response.SingleRunResponse[\"id\"])"}`

I tried a curl to the /actions/runs endpoint and I can see that in workflow_runs, the ids of the different runs are higher than 2147483647

**Screenshots**
<img width="1376" alt="Screenshot 2022-04-26 at 12 18 45" src="https://user-images.githubusercontent.com/82163872/165278941-f544d9d5-ad2e-4bd5-8bdc-61246aab7e71.png">

This is part of the result I get from the /actions/runs endpoint:
![Screenshot 2022-04-26 at 12 37 40](https://user-images.githubusercontent.com/82163872/165282147-e6bd37d2-5d81-46b2-8e30-097ee0e6b66e.png)

**Comment by sddtc** [comment]
I have the same issue

**Comment by unixbps** [comment]
we are also facing same issue, it also failing with Data sync as well.
