### ISSUE TITLE
Add Four Key Metrics understanding and calculation logic in README

### ISSUE THREAD

**Issue by CzarScar** [thoughtworks/metrik#15]
**Is your feature request related to a problem? Please describe.**
I believe Four Key Metrics only defines the results. However, we can use different data to show the status and results. For example, the Mean Time to Restore Service in the DORA report means "For the primary application or service you work on, how long does it generally take to restore service when a service incident or a defect that impacts users occurs(e.g., unplanned outage or service impairment)". After checking the code, I just found the MTTR metrics here is trying to focus on the Pipeline Stages. 

So maybe we can have a clear clarification on README about our understanding on 4KM and calculation logic instead of just put the 4KM link in README?

**Describe the solution you'd like**
Maybe a clear clarification on our 4KM and calculation logic on README or video description will be better.

**Additional context**
I am not sure if we have checked Google's 4KM projects: https://github.com/GoogleCloudPlatform/fourkeys

**Comment by hyrepo** [comment]
Thanks for the suggestion @CzarScar , we've just created a wiki page to elaborate the calculation logic here: https://github.com/thoughtworks/metrik/wiki/How-to-calculate, please refer to this page for now. 

After the wiki was completed, we'll change the README to show more information.

**Comment by CzarScar** [comment]
Hi @hyrepo Thank you for your reply. I will refer to the wiki page.
