### ISSUE TITLE
Need to integrate with GitHubActions

### ISSUE THREAD

**Issue by zhe-zhao** [thoughtworks/metrik#7]
The tool is supposed to support Github Actions

**Describe the solution you'd like**
1. Create, save and verify pipeline configuration (about 3 point)
2. Sync and save data (about 3 point)
3. UI change for configuration page (about 1 point)

**Additional context**

**Comment by karuppiah7890** [comment]
Can people outside the core team work on the issues?

**Comment by zhe-zhao** [comment]
> Can people outside the core team work on the issues?

Hi Karuppiah. Yes, absolutely! Regarding how to map GA workflow executions to our domain models, there are some docs available in our drive. I'm looking to move them to the Wiki very soon

**Comment by kevinlzw** [comment]
Now working on integrating with Github Actions CI/CD tool. 

1. Create, save and verify pipeline configuration (about 3 point)
2. Sync and save data (about 3 point)
3. UI change for config uration page (about 1 point)

**Comment by kevinlzw** [comment]
Mostly done with Github Actions integration
