### ISSUE TITLE
Support for TeamCity 

### ISSUE THREAD

**Issue by shehanster** [thoughtworks/metrik#75]
Would like to have support for TeamCity CI/CD tool.

**Comment by zhe-zhao** [comment]
Hey @shehanster TeamCity is in our backlog but the team don't have enough capacity to work on it now.

I found another interesting tool: https://github.com/cburgmer/buildviz provides graphs detailing runtime behaviour, failures and stability of the pipeline. Thought you might be interested in it

**Comment by shehanster** [comment]
@zhe-zhao Thankyou!
