### ISSUE TITLE
Unable to see the metrics for Jenkins project

### ISSUE THREAD

**Issue by jaideeprana** [thoughtworks/metrik#76]
**Describe the bug**
I am able to integrate the tool with Jenkins pipeline. However when I go to dashboard, I get an error "Handler dispatch failed; nested exception is kotlin.NotImplementedError: An operation is not implemented: Not yet implemented".

**Expected behavior**
Expected to see the metrics data

**Screenshots**
<img width="2048" alt="Screenshot 2021-05-06 at 3 37 40 PM" src="https://user-images.githubusercontent.com/3875065/117281664-86c4f100-ae81-11eb-89fa-2f4b037ac824.png">

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Browser Brave
 - Version 1.23.75

**Comment by zhe-zhao** [comment]
Hi @jaideeprana  thanks for reporting this issue. 

This is caused by a recent change of our data synchronization step. I'm working on the fix now.

**Comment by zhe-zhao** [comment]
@jaideeprana I believe the issue has been fixed in the new release [1.1.1](https://github.com/thoughtworks/metrik/releases/tag/1.1.11).

Could you upgrade the image tag and give it a try?

**Comment by jaideeprana** [comment]
Thanks a lot @zhe-zhao 

I can confirm that this issue has been fix with the release that you mentioned.
