### ISSUE TITLE
Refactor API Test

### ISSUE THREAD

**Issue by hyrepo** [thoughtworks/metrik#80]
**Is your feature request related to a problem? Please describe.**
Current API test is hard to understand and maintain.

**Describe the solution you'd like**
Change to another framework for API test, which is better to maintain

**Comment by zhe-zhao** [comment]
Done.
- Change to RestAssured
- Migrate all existing test cases
- Include API tests in git pre-push hook
- Update CI script to run new tests
- Remove old scripts, and test cases since no longer required.
